import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Nunito, Nunito_Sans } from 'next/font/google';
import "./globals.css";

const nunito = Nunito({
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-nunito',
})

const nunito_sans = Nunito_Sans({
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-nunito-sans',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressContentEditableWarning suppressHydrationWarning>
      <body
        className={cn(nunito.variable, nunito_sans.variable, "")}
        suppressContentEditableWarning suppressHydrationWarning
      >
            <main className="min-h-screen ">
                {children}
            </main>

      </body>
    </html>
  );
}
