import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { Kantumruy_Pro } from 'next/font/google';
import "./globals.css";

const nunito = Kantumruy_Pro({
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-nunito',
})

const nunito_sans = Kantumruy_Pro({
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-nunito-sans',
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(nunito.variable, nunito_sans.variable, "")}
        suppressContentEditableWarning suppressHydrationWarning
      >
        <NextIntlClientProvider>{children}</NextIntlClientProvider>
      </body>
    </html>
  );
}
